In [17]:
import numpy as np

def quantum_state_experiment(num_trials=10):
    for _ in range(num_trials):
        # Random initial superposition
        alpha = np.random.uniform(-1, 1)
        beta = np.sqrt(1 - alpha**2)
        
        # Normalize
        qubit_state = np.array([[alpha], [beta]]) / np.linalg.norm([[alpha], [beta]])
        
        # Hadamard gate
        H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
        
        # Apply gate
        new_state = H @ qubit_state
        
        print("Initial State:\n", qubit_state)
        print("State after Hadamard Gate:\n", new_state)
        print("-" * 30)

quantum_state_experiment()

Initial State:
 [[-0.33636637]
 [ 0.94173121]]
State after Hadamard Gate:
 [[ 0.42805758]
 [-0.90375146]]
------------------------------
Initial State:
 [[-0.55312317]
 [ 0.83309949]]
State after Hadamard Gate:
 [[ 0.19797316]
 [-0.98020744]]
------------------------------
Initial State:
 [[-0.49346786]
 [ 0.86976403]]
State after Hadamard Gate:
 [[ 0.26608157]
 [-0.96395052]]
------------------------------
Initial State:
 [[-0.49987032]
 [ 0.86610026]]
State after Hadamard Gate:
 [[ 0.25896367]
 [-0.96588706]]
------------------------------
Initial State:
 [[-0.66529618]
 [ 0.74657953]]
State after Hadamard Gate:
 [[ 0.05747601]
 [-0.99834689]]
------------------------------
Initial State:
 [[-0.15327477]
 [ 0.98818361]]
State after Hadamard Gate:
 [[ 0.5903697 ]
 [-0.80713296]]
------------------------------
Initial State:
 [[-0.26473378]
 [ 0.96432154]]
State after Hadamard Gate:
 [[ 0.49468325]
 [-0.86907335]]
------------------------------
Initial State:
 [[0.88087335]
 [0.4733520

In [14]:
from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit.quantum_info import Statevector

# Create a quantum circuit 
qc = QuantumCircuit(5)
qc.h(0)  # Apply Hadamard gate to Qubit 0

# Use StatevectorSimulator
simulator = Aer.get_backend('aer_simulator_statevector')  
qc.save_statevector()  
result = simulator.run(qc).result()  
statevector = result.get_statevector()

print("State vector after Hadamard gate:")
print(statevector)


State vector after Hadamard gate:
Statevector([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j, 0.        +0.j,
             0.        +0.j, 0.        +0.j],
            dims=(2, 2, 2, 2, 2))
